In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#load file 
df = pd.read_csv('housePrice_multi.csv')
df.head()

area   bedrooms  age   price
0   2600       3.0   20  360000
1   3000       4.0   15  370000
2   3200       NaN   18  380000
3   3400       3.0   30  390000
4   3600       5.0    8  400000

In [3]:
#find bedrooms colum median
df.bedrooms.median()

4.0

In [4]:
# nan fill up the median value
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area   bedrooms  age   price
0   2600       3.0   20  360000
1   3000       4.0   15  370000
2   3200       4.0   18  380000
3   3400       3.0   30  390000
4   3600       5.0    8  400000
5   4000       6.0    8  410000

In [5]:
# drof the price colum
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [8]:
#regression coefficients or simply the predicted weights,
reg.coef_

array([    53.42975207, -12123.96694215,  -1057.85123967])

In [9]:
reg.intercept_

276652.89256198343

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [10]:
reg.predict([[3000, 3, 40]])

array([358256.19834711])

In [12]:
#genarel equation
53.42975207*3000 + (-12123.96694215*3) + (-1057.85123967*40) + 276652.89256198343

358256.19835873344

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [13]:
reg.predict([[2500, 4, 5]])

array([356442.14876033])