In [1]:
# import library 
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
data=pd.read_csv("sale.csv")

In [3]:
data

Unnamed: 0  Brand  Year  months  days  Qty    Rate    Amount
0               0     27  2018       9     3   50  1500.0   75000.0
1               1     76  2018       9     3   60  1500.0   90000.0
2               2     65  2018       9     3   20  1780.0   35600.0
3               3     57  2018       9     4   60  3250.0  195000.0
4               4     53  2018       9     4  200  1780.0  356000.0
...           ...    ...   ...     ...   ...  ...     ...       ...
17064       17064     28  2021      11     8   24  2270.0   54480.0
17065       17065     41  2021      11     8   28  2550.0   71400.0
17066       17066      9  2021      11     8   18  3200.0   57600.0
17067       17067     41  2021      11     8   21  2550.0   53550.0
17068       17068     28  2021      11     8   24  2250.0   54000.0

[17069 rows x 8 columns]

In [4]:
data.head(12810)

Unnamed: 0  Brand  Year  months  days  Qty    Rate    Amount
0               0     27  2018       9     3   50  1500.0   75000.0
1               1     76  2018       9     3   60  1500.0   90000.0
2               2     65  2018       9     3   20  1780.0   35600.0
3               3     57  2018       9     4   60  3250.0  195000.0
4               4     53  2018       9     4  200  1780.0  356000.0
...           ...    ...   ...     ...   ...  ...     ...       ...
12805       12805     17  2020      12    31   35  2700.0   94500.0
12806       12806     71  2020      12    31   24  2400.0   57600.0
12807       12807     65  2020      12    31   50  1680.0   84000.0
12808       12808     17  2020      12    31   35  2700.0   94500.0
12809       12809     17  2021       1     2   42  2700.0  113400.0

[12810 rows x 8 columns]

In [5]:
train_data = data.iloc[:12809,:]
test_data = data.iloc[12809:,:]

In [6]:
train_data

Unnamed: 0  Brand  Year  months  days  Qty    Rate    Amount
0               0     27  2018       9     3   50  1500.0   75000.0
1               1     76  2018       9     3   60  1500.0   90000.0
2               2     65  2018       9     3   20  1780.0   35600.0
3               3     57  2018       9     4   60  3250.0  195000.0
4               4     53  2018       9     4  200  1780.0  356000.0
...           ...    ...   ...     ...   ...  ...     ...       ...
12804       12804     35  2020      12    31   50  1680.0   84000.0
12805       12805     17  2020      12    31   35  2700.0   94500.0
12806       12806     71  2020      12    31   24  2400.0   57600.0
12807       12807     65  2020      12    31   50  1680.0   84000.0
12808       12808     17  2020      12    31   35  2700.0   94500.0

[12809 rows x 8 columns]

In [7]:
test_data

Unnamed: 0  Brand  Year  months  days  Qty    Rate    Amount
12809       12809     17  2021       1     2   42  2700.0  113400.0
12810       12810     35  2021       1     2   20  1680.0   33600.0
12811       12811     17  2021       1     2   35  2700.0   94500.0
12812       12812     65  2021       1     2   50  1680.0   84000.0
12813       12813     35  2021       1     2  100  1680.0  168000.0
...           ...    ...   ...     ...   ...  ...     ...       ...
17064       17064     28  2021      11     8   24  2270.0   54480.0
17065       17065     41  2021      11     8   28  2550.0   71400.0
17066       17066      9  2021      11     8   18  3200.0   57600.0
17067       17067     41  2021      11     8   21  2550.0   53550.0
17068       17068     28  2021      11     8   24  2250.0   54000.0

[4260 rows x 8 columns]

In [8]:
x=train_data[["Brand","Year","months","days","Qty","Rate"]]
y=train_data['Amount']

In [9]:
# import scaler library and normalize x data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x = scaler.fit_transform(x)

In [10]:
print(x)

[[0.34615385 0.         0.72727273 0.06666667 0.01166945 0.21100917]
 [0.97435897 0.         0.72727273 0.06666667 0.01405096 0.21100917]
 [0.83333333 0.         0.72727273 0.06666667 0.00452489 0.26238532]
 ...
 [0.91025641 1.         1.         1.         0.00547749 0.37614679]
 [0.83333333 1.         1.         1.         0.01166945 0.2440367 ]
 [0.21794872 1.         1.         1.         0.00809717 0.43119266]]


In [11]:
print(y)

0         75000.0
1         90000.0
2         35600.0
3        195000.0
4        356000.0
           ...   
12804     84000.0
12805     94500.0
12806     57600.0
12807     84000.0
12808     94500.0
Name: Amount, Length: 12809, dtype: float64


# random forest

In [12]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators= 100, random_state = 0)

In [13]:
rfr.fit(x,y)

RandomForestRegressor(random_state=0)

In [14]:
train_score = round(rfr.score(x, y) * 100, 2)
train_score

99.49

In [15]:
x1=test_data[["Brand","Year","months","days","Qty","Rate"]]
y1=test_data['Amount']

In [16]:
print(x1)

       Brand  Year  months  days  Qty    Rate
12809     17  2021       1     2   42  2700.0
12810     35  2021       1     2   20  1680.0
12811     17  2021       1     2   35  2700.0
12812     65  2021       1     2   50  1680.0
12813     35  2021       1     2  100  1680.0
...      ...   ...     ...   ...  ...     ...
17064     28  2021      11     8   24  2270.0
17065     41  2021      11     8   28  2550.0
17066      9  2021      11     8   18  3200.0
17067     41  2021      11     8   21  2550.0
17068     28  2021      11     8   24  2250.0

[4260 rows x 6 columns]


In [17]:
print(y1)

12809    113400.0
12810     33600.0
12811     94500.0
12812     84000.0
12813    168000.0
           ...   
17064     54480.0
17065     71400.0
17066     57600.0
17067     53550.0
17068     54000.0
Name: Amount, Length: 4260, dtype: float64


In [18]:
# import scaler library and normalize x data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x1 = scaler.fit_transform(x1)

In [19]:
print(x1)

[[0.21126761 0.         0.         0.03333333 0.01400752 0.49283352]
 [0.46478873 0.         0.         0.03333333 0.00649129 0.26791621]
 [0.21126761 0.         0.         0.03333333 0.01161599 0.49283352]
 ...
 [0.09859155 0.         1.         0.23333333 0.00580799 0.6030871 ]
 [0.54929577 0.         1.         0.23333333 0.00683293 0.45975744]
 [0.36619718 0.         1.         0.23333333 0.00785787 0.39360529]]


In [20]:
y_pred=rfr.predict(x1)
y_pred

array([178959. ,  54355.2, 143459.8, ...,  89902.5,  85500. ,  78632.4])

In [21]:
rf2=r2_score(y1, y_pred)
rf2

0.675826046787797

In [22]:
rfr.predict([[0.46478873,0.,0.,0.03333333,0.00649129,0.26791621]])

array([54355.2])

# decisionTree

In [23]:
from sklearn.tree import DecisionTreeRegressor

In [24]:
dt = DecisionTreeRegressor()

In [25]:
dt.fit(x,y)

DecisionTreeRegressor()

In [26]:
train_score = round(dt.score(x, y) * 100, 2)
train_score

100.0

In [27]:
y_pred=dt.predict(x1)
y_pred

array([180000.,  54600., 139200., ...,  90000.,  85500.,  72000.])

In [28]:
dt2=r2_score(y1, y_pred)
dt2

0.750225570915519

In [29]:
dt.predict([[0.46478873,0.,0.,0.03333333,0.00649129,0.26791621]])

array([54600.])

# LinearRegression

In [30]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [31]:
lr.fit(x,y)

LinearRegression()

In [32]:
train_score = round(lr.score(x, y) * 100, 2)
train_score

61.75

In [33]:
y_pred=lr.predict(x1)
y_pred

array([104983.48874664,  50498.64625661,  95043.61300281, ...,
        80009.15441464,  73409.52761426,  67309.55012955])

In [34]:
lr.predict([[0.46478873,0.,0.,0.03333333,0.00649129,0.26791621]])

array([50498.6548129])

In [35]:
lr2=r2_score(y1, y_pred)
lr2

0.770340878367779

# SVR

In [36]:
from sklearn.svm import SVR

In [37]:
sv=SVR()

In [38]:
sv.fit(x,y)

SVR()

In [39]:
train_score = round(sv.score(x, y) * 100, 2)
train_score

-5.72

In [40]:
y_pred=sv.predict(x1)
y_pred

array([51843.24124076, 51855.54189184, 51843.14773831, ...,
       51831.73675501, 51878.53658521, 51875.71363367])

In [41]:
sv.predict([[0.46478873,0.,0.,0.03333333,0.00649129,0.26791621]])

array([51855.54189187])

In [42]:
sv2=r2_score(y1, y_pred)
sv2

-0.0235764794130624

# qty predict

In [43]:
x=train_data[["Brand","Year","months","days","Amount","Rate"]]
y=train_data["Qty"]

In [44]:
# import scaler library and normalize x data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x = scaler.fit_transform(x)

# Random forest

In [45]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators= 100, random_state = 0)

In [46]:
rfr.fit(x,y)

RandomForestRegressor(random_state=0)

In [47]:
train_score = round(rfr.score(x, y) * 100, 2)
train_score

99.51

In [48]:
x1=test_data[["Brand","Year","months","days","Amount","Rate"]]
y1=test_data["Qty"]

In [49]:
# import scaler library and normalize x data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x1 = scaler.fit_transform(x1)

In [50]:
print(x1)

[[0.21126761 0.         0.         0.03333333 0.01478596 0.49283352]
 [0.46478873 0.         0.         0.03333333 0.00430245 0.26791621]
 [0.21126761 0.         0.         0.03333333 0.01230302 0.49283352]
 ...
 [0.09859155 0.         1.         0.23333333 0.00745538 0.6030871 ]
 [0.54929577 0.         1.         0.23333333 0.00692332 0.45975744]
 [0.36619718 0.         1.         0.23333333 0.00698244 0.39360529]]


In [51]:
print(y1)

12809     42
12810     20
12811     35
12812     50
12813    100
        ... 
17064     24
17065     28
17066     18
17067     21
17068     24
Name: Qty, Length: 4260, dtype: int64


In [52]:
y_pred=rfr.predict(x1)
y_pred

array([18.74,  9.98, 16.52, ...,  8.5 , 10.57, 11.87])

In [53]:
rf2=r2_score(y1, y_pred)
rf2

0.7290559417609683

In [54]:
rfr.predict([[0.21126761,0.,0.,0.03333333,0.01478596,0.49283352]])

array([18.74])

# decision 

In [55]:
dt.fit(x,y)

DecisionTreeRegressor()

In [56]:
train_score = round(dt.score(x, y) * 100, 2)
train_score

100.0

In [57]:
y_pred=dt.predict(x1)
y_pred

array([18., 10., 16., ...,  9., 12., 13.])

In [58]:
dt2=r2_score(y1, y_pred)
dt2

0.7920776367500462

In [59]:
dt.predict([[0.21126761,0.,0.,0.03333333,0.01478596,0.49283352]])

array([18.])

# Linear

In [60]:
lr.fit(x,y)

LinearRegression()

In [61]:
train_score = round(lr.score(x, y) * 100, 2)
train_score

64.19

In [62]:
y_pred=lr.predict(x1)
y_pred

array([ 19.1931058 ,  22.07187746,  13.41767875, ..., -10.47386852,
         1.6055565 ,  13.37716468])

In [63]:
lr2=r2_score(y1, y_pred)
lr2

0.7718113989170556

In [64]:
lr.predict([[0.21126761,0.,0.,0.03333333,0.01478596,0.49283352]])

array([19.19310177])